#!/usr/bin/php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application('FirstPoster', '0.1 (beta)');

$application->add(new App\AddWallCommand());
$application->add(new App\WallListCommand());
$application->add(new App\RemoveWallCommand());
$application->add(new App\PosteCommand());

$application->run();